### ISSUE TITLE
[FEATURE] make Outside Temperature source configurable

### ISSUE THREAD

**Issue by gradius-v** [Neuroquila-n8fall/JunkersControl#23] opened 2022-11-07 20:23 UTC
**Is your feature request related to a problem? Please describe.**
I have no outside temperature sensor hooked up to my Junkers and need a way to inject it from an alternative source.

**Describe the solution you'd like**
Make the outside temperature used a configurable MQTT topic.

**Describe alternatives you've considered**
I currently have a Resistor hooked up instead of the original temperature sensor to stop the heater from freaking out with error CC (no outside temperure sensor).
I have a Netatmo and use this https://github.com/terafin/mqtt-netatmo-bridge to inject the temperature MQTT topic in the old Junkers Control version. (I'm not a programmer, so I'm sure I did it totally wrong, but it works).

**Comment by Neuroquila-n8fall** [comment] 2022-11-07 21:51
That's something I didn't thought of. There is an ambient sensor but it's being used currently for the fastheatup feauture. Will implement a switch to make it available as a replacement.

**Comment by Neuroquila-n8fall** [comment] 2022-11-08 06:25
Oh, as a side note: you can't feed the outside temperature into the controller. That's something the heating controller will send out to the room controller and not the other way around. But we can use the outside temperature to calculate our own adaption values. 

I highly recommend to attach a working sensor to the heating because it makes quite a huge difference in efficiency.

**Comment by gradius-v** [comment] 2022-11-09 06:51
I just remembered this posting https://www.mikrocontroller.net/topic/81265?page=single#6577498
The heating controller seems to not care about the outside temperature und just sends the value to the room controller which in turn uses it to calculate its suggestions and sends them back over to the heating.
Modifying message 0x258 from 0x1 to 0x0 may have the added benefit of the pump stopping once in a while, because at least in my heating device 0x258 = 0x1 makes the pump run permanently, which is bad, as it uses a lot of power.

**Comment by Neuroquila-n8fall** [comment] 2022-11-09 21:04
Understood. Usually if you set the feed to the anti-freeze setting, which is usually 10°C, the pump will stop after a short period of time (default is 3 minutes) regardless of other states (except flame status).

I will look into that and have the option to specify an auxiliary outside reference temperature.

**Comment by Neuroquila-n8fall** [comment] 2022-11-10 07:25
Turns out i already planned for this ahead of time. Could you try, by any chance, if [this feature branch](https://github.com/Neuroquila-n8fall/JunkersControl/tree/feature-outside-temp) is working for you as intended?

Please note the following:
- you have to send your own reference temperature on the "Heating Parameters" mqtt topic. The field is called "AuxiliaryTemperature". See [Heating Parameters Example](https://github.com/Neuroquila-n8fall/JunkersControl/blob/4f1dfaf617069df412e336eb93cdb738b7f0490f/assets/Examples/MQTT_Message_Exchange/Receive/ExampleHeatingParameters.json#L7)
- Switch between internal and external readings using one of the following:
  -  the [configuration](https://github.com/Neuroquila-n8fall/JunkersControl/blob/a00faedc63e0406d32676632d1c123e93e79edca/assets/Templates/Configurations/configuration.json#L28) 
  - using the web ui on-the-fly through "Configuration -> General Settings -> Use your own outside temperature reference instead of that of the heating."
  - You may also use the API for that by sending the config switch on `/api/config/general`
```json 
{
"overrideot": "true"
}
```

**Comment by gradius-v** [comment] 2022-11-11 02:13
That was quick, thanks! But I can't for the life of me figure out how to update just the temperature part of the value in an MQTT topic. Is this even possible ? My tests with MQTT Explorer wipe out all other values.

**Comment by Neuroquila-n8fall** [comment] 2022-11-11 20:29
This heavily depends on the receiving end. This project will just ignore missing values and update those which have been sent. HA for example does that too but complains about missing fields. 
So currently im thinking about moving everything what mqtt offers to the REST api for such cases where you want to update a single value for debugging for example.

**Comment by gradius-v** [comment] 2022-11-19 07:43
I figured it out and heating works as intended. :)

**Comment by gradius-v** [comment] 2023-01-08 03:20
Can you add this feature to the latest version ?

**Comment by Neuroquila-n8fall** [comment] 2023-02-12 11:23
Feature is merged. Thank you @gradius-v for the input 👍

**Closed by Neuroquila-n8fall** 2023-02-12 11:23 UTC
Labels: enhancement
